CONFIG_ANALOG_INPUT_LOG_DBG_RAW=y
CONFIG_ANALOG_INPUT_LOG_DBG_REPORT=y

CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_POINTING=y

# Enable Analog Input
CONFIG_ADC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y

CONFIG_INPUT=y

#faulty oscillator
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y