CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_CDC_ACM=y

CONFIG_SERIAL=y

CONFIG_CONSOLE=y
CONFIG_USB_UART_CONSOLE=y

CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_POINTING=y

# Enable Analog Input
CONFIG_ADC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y

CONFIG_INPUT=y